name: Bug Report
description: File a bug report.
title: "[Bug] - "
labels: ["bug", "triage"]
projects: ["3x1t-5tyl3/exitiantweaks"]
assignees:
  - 3x1t-5tyl3

body:
- type: markdown
  attributes:
    value: "## Please give as much info as you can!"
- type: checkboxes
  id: existing-issue-check
  attributes:
    label: Check all that apply
    options:
      - label: I checked that the version is in range of supported versions.
        required: true
      - label: I made sure to check if an issue already exists
        required: true
      - label: I uploaded a "latest.log" found in the "logs" folder to [mclogs](https://mclo.gs/)
- type: input
  id: mc-log
  attributes:
    label: Link to that log
    description: "Please upload a log as seen above"
    placeholder: "https://mclo.gs/whatever"
  validations:
    required: true
- type: input
  id: mc-ver
  attributes:
    label: Minecraft version
    description: "Which version of minecraft?"
    placeholder: "1.21.x"
  validations:
    required: true
- type: input
  id: loader-ver
  attributes:
    label: What loader and version
    description: "What's the mod's loader and the version for it?"
    placeholder: "NeoForge 21.x.x.x"
  validations:
    required: true
- type: input
  id: mod-ver
  attributes:
    label: Mod version
    description: "What's the mod's version you're having an issue with?"
    placeholder: "1.x.x"
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: addit
  attributes:
    label: Additional info
    description: "Any additional info you think might be important"
    value: "Anything of note.."
    render: bash
  validations:
    required: false
